### ISSUE TITLE
Error at launch : Unable to load extension

### ISSUE THREAD

**Issue by pmancele** [catie-aq/cookiecutter_mbed-os-app#25]
Unable to load extension: No module named 'local_extensions'

**Comment by bperraudin** [comment]
@pmancele Can you please give me the Cookiecutter version you're using?

Local extensions have been added to the [recent 2.1 version](https://cookiecutter.readthedocs.io/en/stable/advanced/local_extensions.html).

**Comment by pmancele** [comment]
@bperraudin Indeed it has been solved by upgrading the cookiecutter version.

I'm closing the issue
